language: php
php:
  - 5.6
  - hhvm
before_script:
  - cp ./config/database.example.php ./config/database.php
  - composer install
script:
  - phpunit

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
